# Afterglow color scheme

background            #F4EEE1
foreground            #24163B
cursor                #C3228E
cursor_text_color     #F4EEE1
selection_background  #DFC2AA
selection_foreground  #24163B
url_color             #1D7187

color0   #F4EEE1
color1   #B12531
color2   #22775B
color3   #A25410
color4   #1D7187
color5   #8930A6
color6   #AE296B
color7   #574979
color8   #CDAEA2
color9   #B12531
color10  #22775B
color11  #A25410
color12  #1D7187
color13  #8930A6
color14  #AE296B
color15  #24163B
