# Foreglow color scheme

background            #161221
foreground            #E8E3F2
cursor                #F471C8
cursor_text_color     #161221
selection_background  #3D2556
selection_foreground  #E8E3F2
url_color             #75C6D7

# Normal colors
color0   #161221
color1   #E46772
color2   #6BC7A8
color3   #F2A65A
color4   #75C6D7
color5   #CB81E4
color6   #EC93BF
color7   #A49BBF

# Bright colors
color8   #322C44
color9   #E46772
color10  #6BC7A8
color11  #F2A65A
color12  #75C6D7
color13  #CB81E4
color14  #EC93BF
color15  #E8E3F2
